### PR TITLE
Fix/client created bugs

### PR DESCRIPTION
**Pull request by simonabadoiu**

### CODE REVIEW

**Comment by fabiokr** [comment]
By the way I manually applied the changes from https://github.com/cloudflare/webcm/pull/104 since this branch does not seem to include that yet, and I it was still not triggering `pageShow`.

**Comment by simonabadoiu** [comment]
I pushed a small fix, but besides that, there's another reason why the example is not working:
- `clientcreated` events are called only when a browser is loading the website for the first time - this event listener will be called again only if the component name doesn't exist in `webcm_clientcreated` cookie or the cookie doesn't exist at all
- client events (like `pageShow`,` mousedown`, etc) are attached per page load (they are lost on the next page load unless they are attached again) 

So this means you are attaching `pageShow` on `clientcreated`, then you probably navigate to another page or reload the current one to test `pageshow` event listener, but the listener is lost on reload and never created again because of what I explained above. You should attach `pageshow` on `pageview` and this will work.

**Comment by fabiokr** [comment]
> export default async function (manager, _settings) {
>   manager.addEventListener('request', (payload) => { });
>   manager.addEventListener('clientcreated', ({ client }) => { client.attachEvent('pageShow'); });
>   manager.createEventListener('pageShow', (payload) => { console.log("PAGESHOW", payload) });
> }

Thanks for the clarification. I'm now testing the following with this branch:

```
export default async function (manager, _settings) {
  manager.addEventListener('pageview', ({ client }) => { client.attachEvent('pageShow'); });
  manager.createEventListener('pageShow', (payload) => { console.log("PAGESHOW", payload) });
}
```

But that gives me this error:

```
for (const componentName of Object.keys(manager.listeners[eventName])) {

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at handleClientCreated (/home/fabio/Dev/crazyegg/zaraz-component/dev/webcm/lib/server.ts:68:40)
```

It sounds like `manager.listeners[eventName]` is null there.

**Comment by simonabadoiu** [comment]
@fabiokr fixed and merged and released

**Pull request merged**
